### ISSUE TITLE
Rebrand towards colours of Open Knowledge Belgium

### ISSUE THREAD

**Issue by pietercolpaert** [oSoc15/website#1]
The logo of Open Knowledge Belgium has changed, as did the colours. You can see how it looks like right now at http://openknowledge.be and http://okfn.org

Colours:
- #dfdfdf (light gray → for light backgrounds for e.g., a navbar)
- #2d2d2d (dark gray → for dark backgrounds with white text)
- #7ab800 (green: e.g., for hyperlinks)
- #f00 (red: e.g., for call to actions)
- Body text colour: #2d2d2d and on a green or dark gray background: white

New logo:
 _todo @pjpauwels_

**Comment by PieterJanPauwels** [comment]
Our new logo branding has no inner core circle, just the letters BE, to be found on:  https://drive.google.com/open?id=0ByBC-sFwdwtJTnNuU25ETzRiTDQ&authuser=0

**Comment by Dobbelsteen** [comment]
Rebranding complete, only using white, dark-grey, green and blue (for the links)

Also added favicons for various devices with the new logo without core
