### ISSUE TITLE
Probleem met cities/date (mobile) en overflow op body

### ISSUE THREAD

**Issue by wesobi** [oSoc15/website#17]
# Issue:

![schermafbeelding 2015-04-20 om 15 31 04](https://cloud.githubusercontent.com/assets/9094522/7230948/400bfd12-e772-11e4-82e2-3dc02b76efde.png)
# Solution:

![schermafbeelding 2015-04-20 om 15 16 27](https://cloud.githubusercontent.com/assets/9094522/7230976/7a3282fe-e772-11e4-8a4f-1e399eb22286.png)
## Daarnaast ook nog:

body{
overflow-x:hidden;}

Bovenstaande lijkt voor mij te werken, met daarnaast ook geen zichtbare afwijkingen op andere plaatsen of elementen. Heb het maar vluchtig overlopen want ik zit in de les!
# Resultaat:

![schermafbeelding 2015-04-20 om 15 39 19](https://cloud.githubusercontent.com/assets/9094522/7231097/61754408-e773-11e4-8792-cf6e177135ce.png)

**Comment by Dobbelsteen** [comment]
Thanks for the suggestion!
I fixed it by changing the grid from 2 columns to 1 for now, since there were also some alignment issues elsewhere on mobile (students, partners)

**Comment by wesobi** [comment]
I saw that as well after downloading a zip! Noticed the alignment issues as well. I will give it a look tonight, but it might be easier to work with a center/justify alignment (justify may not work if they are large blocks of text), and adding a width to it so that it looks more "slick". Just a suggestion of course!

**Comment by pietercolpaert** [comment]
Is it fixed?

**Comment by Dobbelsteen** [comment]
I made another issue right before this one with another fix for the same thing.
For now it's fixed, but not with this method.

**Comment by Dobbelsteen** [comment]
I tried your solution, and while it works, there is still a possibility that the alignments mess up.
I've decided to keep the 1 column grid on mobile, so that alignments are always neat.
