### ISSUE TITLE
metadata for social media and SEO

### ISSUE THREAD

**Issue by pietercolpaert** [oSoc15/website#19]
- [x] Can you check what appears on Twitter as a twitter card and make it more awesome?
- [x] Same with Facebook and opengraph
- [x] We should create a JSON-LD which we can add in the header with the necessary events. See more: https://developers.google.com/structured-data/events/venues

**Comment by Dobbelsteen** [comment]
For now I'll be using the oSoc logo for the twitter card, but it might be fancier to use a bigger photo with the logo as overlay.
Ditto for Facebook and OG.
I'm not familiar with JSON-LD yet, but I'll look into it

**Comment by pietercolpaert** [comment]
Great! You can check the boxes when you're done with something ;)

**Comment by Dobbelsteen** [comment]
I updated the Twitter Card and FB OG, but haven't been able to test it on a live website.
According to the Twitter card validator, the card is valid, but I can't say for 100%, if anyone could double check, that'd be great.

Update: Managed to test the Twitter Card, it looks nice but the description is a bit too long. 

> "Open Summer of code is a 3 week programme in Belgian cities during the summer of 2015. The goal: provide Belgian based students the training, network and support necessary to transform open innovation projects into powerful real-world services." 

This should be shortened to 198 character if possible

**Comment by Dobbelsteen** [comment]
I've written a sample JSON-LD file which can be extended when we have more details about the events.
This also contains a reference to Open Knowledge Belgium, and has 2 example subEvents, in this case, what we'll be doing the first day at oSoc15.

Is this what you had in mind @pietercolpaert ?

``` json
[{
  "@context" : "http://schema.org",
  "@type" : "Event",
  "name" : "Open Summer of code 2015 Starts!",
  "startDate" : "2014-07-06T09:00",
  "endDate" : "2014-07-06T17:00",
  "organizer" : {
        "@id" : "https://opencorporates.com/id/companies/be/0845419930",
        "@type": "Organization",
        "name": "Open Knowledge Belgium",
        "url" : "http://www.openknowledge.be"
  },
  "location" : { 
     "@type" : "Place",
     "name" : "TBA",
     "address" : "TBA"
  },
  "image" : "http://2015.summerofcode.be/images/socialmedia/logo.png",
  "subEvent" : [{
        "@type" : "Event",
        "name" : "Introduction",
        "startDate" : "2014-07-06T09:30",
        "endDate" : "2014-07-06T10:30",
        "organizer" : "https://opencorporates.com/id/companies/be/0845419930",
        "location" : { 
           "@type" : "Place",
           "name" : "TBA",
           "address" : "TBA"
        }
    }, 
    {
        "@type" : "Event",
        "name" : "Project assignment",
        "startDate" : "2014-07-06T11:00",
        "endDate" : "2014-07-06T12:00",
        "organizer" : "https://opencorporates.com/id/companies/be/0845419930",
        "location" : { 
           "@type" : "Place",
           "name" : "TBA",
           "address" : "TBA"
        }
    }]
}]
```

**Comment by pietercolpaert** [comment]
- open Summer of code - small c ;-)
- no stopdate for the parent event?
- our zipcode is 9050
- Otherwise: yes - It is what I intended :+1:

**Comment by pietercolpaert** [comment]
Another problem: http://schema.org/organizer is not a name but an object of an "@type"  Person or Organization. This means it needs to be an object which has a name and maybe a http://schema.org/url

You did it right the first time, but not the second time. You can refer to the object using URIs. (e.g., from now on, we could always use the URI http://openknowledge.be/#id for our organization, or we could use the ID from open corporates: https://opencorporates.com/id/companies/be/0845419930)

**Comment by Dobbelsteen** [comment]
Is it possible to just reference the same organizer from the parentEvent in the subEvents?
Or if I just say like 

``` json
"organizer" : {
        "@type": "Organization",
        "name": "Open Knowledge Belgium",
        "url" : "http://www.openknowledge.be"
  }
```

It should reference to the organization I declared more extensive earlier, right?

Also, does the parentEvent end at the final day of oSoc (31 July), or bundle the events per week or per day

**Comment by pietercolpaert** [comment]
using URIs:

``` javascript
//First mention:
"organizer" : {
        "@id" : "https://opencorporates.com/id/companies/be/0845419930",
        "@type": "Organization",
        "name": "Open Knowledge Belgium",
        "url" : "http://www.openknowledge.be"
  }
//...
//later mention:
"organizer" : "https://opencorporates.com/id/companies/be/0845419930"
```

**Comment by Dobbelsteen** [comment]
Ok, awesome!

Updated JSON+LD

``` json
[{
  "@context" : "http://schema.org"
   ,
  "@type" : "Event",
  "name" : "Open Summer of code 2015 Starts!",
  "startDate" : "2014-07-06T09:00",
  "endDate" : "2014-07-06T17:00",
  "organizer" : {
        "@id" : "https://opencorporates.com/id/companies/be/0845419930",
        "@type": "Organization",
        "name": "Open Knowledge Belgium",
        "url" : "http://www.openknowledge.be"
  },
  "location" : {
     "@type" : "Place",
     "name" : "TBA",
     "address" : "TBA"
  },
  "image" : "http://2015.summerofcode.be/images/socialmedia/logo.png",
  "subEvent" : [{
        "@type" : "Event",
        "name" : "Introduction",
        "startDate" : "2014-07-06T09:30",
        "endDate" : "2014-07-06T10:30",
        "organizer" : { "@id": "https://opencorporates.com/id/companies/be/0845419930"},
        "location" : { 
           "@type" : "Place",
           "name" : "TBA",
           "address" : "TBA"
        }
    }, 
    {
        "@type" : "Event",
        "name" : "Project assignment",
        "startDate" : "2014-07-06T11:00",
        "endDate" : "2014-07-06T12:00",
        "organizer" :{ "@id": "https://opencorporates.com/id/companies/be/0845419930"},
        "location" : { 
           "@type" : "Place",
           "name" : "TBA",
           "address" : "TBA"
        }
    }]
}]
```
